"use client";

/**
 * "Enable Profiles" wizard — turns the previously-manual setup into one click.
 *
 *   1. Generate a strong key client-side (Web Crypto)
 *   2. User reviews the key + saves it somewhere they trust
 *   3. User picks ONE of two paths:
 *        a) Apply automatically → POST /v1/profiles/setup writes the key to .env
 *           and appends the profiles block to gateway.yml on the gateway's host
 *        b) Show me snippets → falls back to the old paste-and-restart flow
 *   4. After either path, the user manually restarts the gateway (we can't)
 *
 * The key is generated by the browser via crypto.getRandomValues — same entropy
 * source the gateway would use server-side, but we don't trust the network with
 * it until the user opts into the auto-apply call.
 */
import { useState, useEffect } from "react";
import { AlertCircle, Check, Copy, FileText, KeyRound, Loader2, Play } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { CodeBlock } from "./code-block";
import { enableProfilesSetup, type EnableProfilesResult } from "@/lib/api";

function generateKeyBase64(): string {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  let s = "";
  for (const b of bytes) s += String.fromCharCode(b);
  return btoa(s);
}

type Status = "idle" | "applying" | "applied" | "error";

export function SetupEncryptionKeyDialog() {
  const [open, setOpen] = useState(false);
  const [key, setKey] = useState<string | null>(null);
  const [copiedKey, setCopiedKey] = useState(false);
  const [showManual, setShowManual] = useState(false);
  const [status, setStatus] = useState<Status>("idle");
  const [errMsg, setErrMsg] = useState<string | null>(null);
  const [result, setResult] = useState<EnableProfilesResult | null>(null);

  useEffect(() => {
    if (open) {
      setKey(generateKeyBase64());
      setCopiedKey(false);
      setShowManual(false);
      setStatus("idle");
      setErrMsg(null);
      setResult(null);
    } else {
      setTimeout(() => setKey(null), 300);
    }
  }, [open]);

  async function handleCopyKey() {
    if (!key) return;
    try {
      await navigator.clipboard.writeText(key);
      setCopiedKey(true);
      setTimeout(() => setCopiedKey(false), 2000);
    } catch {
      // Silent — user can still select the rendered code
    }
  }

  async function handleAutoApply() {
    if (!key) return;
    setStatus("applying");
    setErrMsg(null);
    try {
      const r = await enableProfilesSetup(key);
      setResult(r);
      setStatus("applied");
    } catch (e) {
      setErrMsg(e instanceof Error ? e.message : "Setup failed");
      setStatus("error");
    }
  }

  const yamlSnippet = `# add this block to gateway.yml
profiles:
  enabled: true
  filesystem:
    path: ./profiles
  encryption:
    keyEnv: BG_ENCRYPTION_KEY`;

  const shellSnippet = key
    ? `# 1. set the key in your environment
export BG_ENCRYPTION_KEY="${key}"

# 2. restart the gateway
browser-gateway serve

# or, if you use a .env file:
echo 'BG_ENCRYPTION_KEY="${key}"' >> .env`
    : "";

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger
        render={
          <Button size="sm">
            <KeyRound className="size-3.5 mr-1.5" />
            Enable Profiles
          </Button>
        }
      />
      <DialogContent className="sm:max-w-xl">
        <DialogHeader className="min-w-0">
          <DialogTitle className="flex items-center gap-2">
            <KeyRound className="size-4 text-muted-foreground" />
            Enable Profiles
          </DialogTitle>
          <DialogDescription>
            Profiles encrypt and persist browser sessions across runs. To enable, the
            gateway needs an encryption key. We&apos;ll generate one in your browser and
            (optionally) write it to your gateway&apos;s <code className="font-mono">.env</code> + <code className="font-mono">gateway.yml</code>.
          </DialogDescription>
        </DialogHeader>

        {status === "applied" && result ? (
          <SuccessPanel result={result} />
        ) : (
          <div className="space-y-4 min-w-0">
            <div className="space-y-1.5">
              <div className="flex items-center justify-between">
                <label className="text-[12px] font-medium text-foreground/80">
                  Your new encryption key
                </label>
                <Button size="sm" variant="ghost" onClick={handleCopyKey} className="h-6 px-2 text-[11px]">
                  {copiedKey ? (
                    <><Check className="size-3 mr-1" />copied</>
                  ) : (
                    <><Copy className="size-3 mr-1" />copy</>
                  )}
                </Button>
              </div>
              <code
                className="block bg-black/40 border border-border/40 rounded px-3 py-2 font-mono text-[11.5px] text-foreground/90 break-all select-all"
                onClick={(e) => {
                  const range = document.createRange();
                  range.selectNodeContents(e.currentTarget);
                  window.getSelection()?.removeAllRanges();
                  window.getSelection()?.addRange(range);
                }}
              >
                {key ?? "…"}
              </code>
              <div className="flex items-start gap-2 mt-2 px-2 py-1.5 rounded bg-muted/40 border border-border/60 text-[11.5px]">
                <AlertCircle className="size-3.5 text-muted-foreground shrink-0 mt-0.5" />
                <p className="text-foreground/85 leading-relaxed">
                  <span className="font-medium text-foreground">Save this key now.</span>{" "}
                  We won&apos;t show it again. If you lose it, all stored profiles become
                  permanently unreadable.
                </p>
              </div>
            </div>

            {!showManual ? (
              <div className="space-y-2">
                <p className="text-[12px] font-medium text-foreground/80">
                  Now apply it to your gateway
                </p>
                <Button
                  onClick={handleAutoApply}
                  disabled={status === "applying" || !key}
                  className="w-full"
                  size="sm"
                >
                  {status === "applying" ? (
                    <><Loader2 className="size-3.5 mr-1.5 animate-spin" />Writing files…</>
                  ) : (
                    <><Play className="size-3.5 mr-1.5" />Apply automatically (writes .env + gateway.yml)</>
                  )}
                </Button>
                {errMsg && (
                  <p className="text-[12px] text-foreground px-1">{errMsg}</p>
                )}
                <button
                  onClick={() => setShowManual(true)}
                  className="text-[11.5px] text-muted-foreground hover:text-foreground underline underline-offset-2"
                >
                  Or set it up manually instead
                </button>
              </div>
            ) : (
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <p className="text-[12px] font-medium text-foreground/80">
                    Manual setup. Paste these and restart.
                  </p>
                  <button
                    onClick={() => setShowManual(false)}
                    className="text-[11.5px] text-muted-foreground hover:text-foreground underline underline-offset-2"
                  >
                    Back to auto-apply
                  </button>
                </div>
                <CodeBlock lang="bash" filename=".env + restart" code={shellSnippet} />
                <CodeBlock lang="yaml" filename="gateway.yml" code={yamlSnippet} />
              </div>
            )}
          </div>
        )}

        <DialogFooter className="flex-row sm:flex-row gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => setOpen(false)}
            className="flex-1 sm:flex-none"
          >
            {status === "applied" ? "Close" : "Cancel"}
          </Button>
          {status !== "applied" && (
            <Button
              size="sm"
              disabled={!copiedKey && status !== "applying"}
              onClick={() => {
                setOpen(false);
              }}
              className="flex-1 sm:flex-none"
            >
              <Check className="size-3.5 mr-1.5" />
              I&apos;ve saved my key
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function SuccessPanel({ result }: { result: EnableProfilesResult }) {
  return (
    <div className="space-y-3 min-w-0">
      <div className="flex items-start gap-3 px-3 py-2.5 rounded bg-muted/40 border border-border/60">
        <Check className="size-4 text-foreground shrink-0 mt-0.5" />
        <div className="space-y-1 text-[12.5px]">
          <p className="font-medium text-foreground">Setup complete</p>
          <p className="text-muted-foreground leading-relaxed">
            Now <span className="font-medium text-foreground">restart the gateway</span> for the changes to take effect. Stop the process (<code className="font-mono text-foreground/90 bg-black/40 px-1 py-0.5 rounded text-[11px]">Ctrl+C</code> in the terminal where you started it) and launch it again with the same command.
          </p>
        </div>
      </div>

      <div className="text-[12px] space-y-2">
        <FileStatus
          icon={<FileText className="size-3.5 text-muted-foreground" />}
          label="Environment file"
          path={result.envPath}
          status={
            result.envWritten
              ? { text: "key added", tone: "good" }
              : result.envAlreadyHadKey
              ? { text: "already had BG_ENCRYPTION_KEY. Left untouched.", tone: "info" }
              : { text: "no change", tone: "info" }
          }
        />
        <FileStatus
          icon={<FileText className="size-3.5 text-muted-foreground" />}
          label="Gateway config"
          path={result.configPath}
          status={
            result.configWritten
              ? { text: "profiles block written", tone: "good" }
              : result.configAlreadyHadBlock
              ? { text: "already had a profiles block. Left untouched.", tone: "info" }
              : { text: "no change", tone: "info" }
          }
        />
      </div>
    </div>
  );
}

function FileStatus(props: {
  icon: React.ReactNode;
  label: string;
  path: string;
  status: { text: string; tone: "good" | "info" };
}) {
  return (
    <div className="px-3 py-2 rounded border border-border/40 bg-black/20">
      <div className="flex items-center gap-2 min-w-0">
        {props.icon}
        <span className="text-foreground/90 font-medium">{props.label}</span>
        <code className="font-mono text-[11px] text-muted-foreground truncate" title={props.path}>
          {props.path}
        </code>
      </div>
      <p className={`mt-0.5 text-[11.5px] ${props.status.tone === "good" ? "text-foreground" : "text-muted-foreground"}`}>
        {props.status.text}
      </p>
    </div>
  );
}
